sudo: false
language: python
python:
  - "2.7"
before_install:
  - git submodule update --init
  - rvm use 2.2.3 --install --fuzzy
  - wget -O jsbsim.tar.gz http://jsbsim.cvs.sourceforge.net/viewvc/jsbsim/?view=tar
  - tar -xvf jsbsim.tar.gz
install:
 - cd jsbsim/JSBSim/
 - ./autogen.sh
 - ./configure
 - make
 - export PATH=$PATH:$PWD/src/
 - cd ../..
 - gem install --no-document jekyll
 - pip install --use-wheel jupyter
 - pip install --use-wheel numpy
 - pip install --use-wheel matplotlib
script:
 - cd case-01-dragless_sphere
 - make
 - cd ../docs
 - make
 - x=$(for i in `git log --all --pretty=format:{\"%h\":\"%ad\"},`; do echo -n "${i}"; done| sed 's/,$//') ; echo "["$x"]" > _site/git.json
 - ./deploy.sh
