sudo: true
language: python
python:
  - "2.7"
before_install:
  - rvm use 2.2.3 --install --fuzzy
  - wget -O jsbsim.tar.gz http://jsbsim.cvs.sourceforge.net/viewvc/jsbsim/?view=tar
  - tar -xvf jsbsim.tar.gz
install:
 - cd jsbsim/JSBSim/
 - ./autogen.sh
 - ./configure
 - sudo make install
 - cd ../..
 - gem install --no-document jekyll
 - pip install --use-wheel jupyter
 - pip install --use-wheel numpy
 - pip install --use-wheel matplotlib
script:
 - cd case-01-dragless_sphere
 - make
